DEV-3590: Rollback Prevention
automata-network/automata-on-chain-pccs pull request #15
Opened 2024-12-18 06:25 UTC by preston4896

https://atanet.atlassian.net/browse/DEV-3590

2024-12-27 02:21 UTC, preston4896 commented on src/automata_pccs/AutomataFmspcTcbDao.sol
> +    }
attestation id for timestamp won't be explicitly needed, and this can be easily computed anyway.

2025-01-02 11:16 UTC, melynx requested changes
Please make sure that each PR only implements a single thing. If you want to refactor, please do it in another PR.

2025-01-02 11:16 UTC, melynx commented on src/bases/PcsDao.sol
> +            bool replaced = existingCertNotValidBefore > currentCert.validityNotBefore;
why is this called replaced?

2025-01-02 11:16 UTC, melynx commented on src/bases/PcsDao.sol
> +            bool replaced = existingCrlNotValidBefore > currentCrl.validityNotBefore;
same as above

2025-01-02 11:16 UTC, melynx commented on src/helpers/X509Helper.sol
> +        (validityNotBefore, validityNotAfter) = _getValidity(der, tbsPtr);
How do you know if tbsPtr is pointing to the correct node?

2025-01-02 11:16 UTC, melynx commented on src/helpers/X509Helper.sol
> +    function getCertValidity(bytes calldata der) external pure returns (uint256 validityNotBefore, uint256 validityNotAfter) {
What is this method used for and where is it used?

2025-01-02 11:16 UTC, melynx commented on src/automata_pccs/AutomataFmspcTcbDao.sol
> +    function _cacheTcbInfoIssueEvaluation(bytes32 tcbKey, uint64 issueDateTimestamp, uint32 evaluationDataNumber) internal override {
Why do you use the term cache?

2025-01-02 11:16 UTC, melynx commented on src/bases/PckDao.sol
> +            bool replaced = existingCertNotValidBefore > pck.validityNotBefore;
Why is it called replaced here?

2025-01-02 11:16 UTC, melynx commented on src/bases/EnclaveIdentityDao.sol
> +        if (id == uint256(EnclaveId.TD_QE) && version < 4) {
I'll constrain it to 4 and 5, cause at this current moment all other versions are invalid and we have no idea in the future Intel will actually support TD_QE in version 6.

2025-01-03 01:58 UTC, preston4896 commented on src/bases/PcsDao.sol
> +            bool replaced = existingCertNotValidBefore > currentCert.validityNotBefore;
because I thought the existing collateral(s) replace the one(s) that is about to be upserted, due to it not being the latest version. But i guess i could just rename all `replaced` variables as `bool outOfDate` instead, calling it as it is...

2025-01-03 05:16 UTC, preston4896 commented on src/bases/PcsDao.sol
> +            bool replaced = existingCrlNotValidBefore > currentCrl.validityNotBefore;
all `replaced` boolean variables renamed as `outOfDate` in commit [`6eb7099`](https://github.com/automata-network/automata-on-chain-pccs/pull/15/commits/6eb7099e3117aab71518fd1d9ea0cb64b0d2023a)

2025-01-03 05:17 UTC, preston4896 commented on src/bases/PckDao.sol
> +            bool replaced = existingCertNotValidBefore > pck.validityNotBefore;
[`6eb7099`](https://github.com/automata-network/automata-on-chain-pccs/pull/15/commits/6eb7099e3117aab71518fd1d9ea0cb64b0d2023a)

2025-01-03 05:28 UTC, preston4896 commented on src/bases/EnclaveIdentityDao.sol
> +        if (id == uint256(EnclaveId.TD_QE) && version < 4) {
[eb1a642](https://github.com/automata-network/automata-on-chain-pccs/pull/15/commits/eb1a64271d8a4d9ed9cbb4ed69f6054ff20ff8a5)

2025-01-03 05:29 UTC, preston4896 commented on src/bases/PcsDao.sol
> +            bool replaced = existingCrlNotValidBefore > currentCrl.validityNotBefore;
[6eb7099](https://github.com/automata-network/automata-on-chain-pccs/pull/15/commits/6eb7099e3117aab71518fd1d9ea0cb64b0d2023a)

2025-01-03 05:29 UTC, preston4896 commented on src/bases/PckDao.sol
> +            bool replaced = existingCertNotValidBefore > pck.validityNotBefore;
[6eb7099](https://github.com/automata-network/automata-on-chain-pccs/pull/15/commits/6eb7099e3117aab71518fd1d9ea0cb64b0d2023a)

2025-01-03 05:30 UTC, preston4896 commented on src/helpers/X509Helper.sol
> +    function getCertValidity(bytes calldata der) external pure returns (uint256 validityNotBefore, uint256 validityNotAfter) {
This method is used for reading the validity for existing PCK and PCS CA Certificates. [c79d092](https://github.com/automata-network/automata-on-chain-pccs/pull/15/commits/c79d092d976a43ea462bf61714e0b49b2a5e5964)

2025-01-03 05:35 UTC, preston4896 commented on src/automata_pccs/AutomataFmspcTcbDao.sol
> +    function _cacheTcbInfoIssueEvaluation(bytes32 tcbKey, uint64 issueDateTimestamp, uint32 evaluationDataNumber) internal override {
Maybe "caching" isn't the appropriate term for this action. But the goal is to store a copy of the issued timestamp and evaluation number, to reduce the read amount for validity check.

I can just rename it as `_storeTcbInfoIssueEvaluation`

2025-01-03 06:59 UTC, preston4896 commented on src/automata_pccs/AutomataFmspcTcbDao.sol
> +    function _cacheTcbInfoIssueEvaluation(bytes32 tcbKey, uint64 issueDateTimestamp, uint32 evaluationDataNumber) internal override {
[9661dc2](https://github.com/automata-network/automata-on-chain-pccs/pull/15/commits/9661dc20b2c228cb33480ca5538485f243e911db)

2025-01-03 07:07 UTC, preston4896 commented on src/automata_pccs/AutomataFmspcTcbDao.sol
> +    }
attestationId for tcb evaluation not needed

2025-01-03 08:43 UTC, melynx approved these changes
LGTM

2025-01-03 08:44 UTC, merged